List stdlib as dependency
tubemogul/puppet-aerospike pull request #29
Opened 2017-01-14 19:48 UTC by deric

`puppetlabs-stdlib` should be listed as module's dependency. The lower version bound was guessed by the first version where `is_integer` function appeared.

2017-01-15 23:01 UTC, aerostitch commented
This has been removed after one of the 1st commits because the forge was issuing warnings in the metadata quality saying that stdlib was shipped by default.
I've seen modules lately that had that dependency and no warning about it so I guess it's ok to re-add it then.

2017-01-15 23:10 UTC, aerostitch requested changes

2017-01-15 23:10 UTC, aerostitch commented on metadata.json
> +      "name": "puppet-archive",
This should not be changed.

2017-01-15 23:10 UTC, aerostitch commented on metadata.json
> +      "name": "puppetlabs-stdlib",
Please change that to:
```
"name": "puppetlabs/stdlib",
```

Thanks! :)

2017-01-16 09:15 UTC, deric commented
Sorry about that. The documentation is quite confusing about using slash vs. dash. There are even [some examples of dependencies with dash](https://docs.puppet.com/puppet/latest/modules_fundamentals.html#writing-modules). I'm always forgetting which one is preffered.

2017-01-17 18:57 UTC, aerostitch approved these changes

2017-01-17 18:57 UTC, merged

2017-01-17 18:58 UTC, aerostitch commented
Sounds good.
I still have a few changes I want to make and I'll release that soon.
Thanks for the contribution!